"""empty message

Revision ID: 16d731f826de
Revises: 
Create Date: 2020-02-24 00:50:14.160777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16d731f826de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MGS_NODE',
    sa.Column('node_name', sa.String(length=100), nullable=False),
    sa.Column('ip_addr', sa.String(length=50), nullable=True),
    sa.Column('cert_key', sa.Text(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('is_idpw_auth', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('node_name'),
    sa.UniqueConstraint('node_name')
    )
    op.create_table('MGS_USER',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('username')
    )
    op.create_table('MGS_LEASE',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('node_name', sa.String(length=100), nullable=True),
    sa.Column('expire_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_name'], ['MGS_NODE.node_name'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MGS_LEASE')
    op.drop_table('MGS_USER')
    op.drop_table('MGS_NODE')
    # ### end Alembic commands ###
